# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: admin
    ports: 3307:3306
    volumes: 
      - mariadb:/var/lib/mysql
volumes:
  - mariadb: