# Use root/example as user/password credentials
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - TZ=Asia/Seoul
    volumes: 
      - mariadb:/var/lib/mysql
    ports: 
      - "3306:3306"
volumes:
  mariadb: